### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by tatecarson** [experimentalDataAesthetics/play-splom#8]
When npm run dev  
`Error: Cannot find module 'babel-register'
[0]     at Function.Module._resolveFilename (module.js:325:15)
[0]     at Function.Module._load (module.js:276:25)
[0]     at Module.require (module.js:353:17)
[0]     at module.js:498:12
[0]     at Array.forEach (native)
[0]     at Function.Module._preloadModules (module.js:497:12)
[0]     at Function.startup.preloadModules (node.js:861:38)
[0]     at startup (node.js:117:17)
[0]     at node.js:968:3
[0] 
[0] npm
[0]  ERR! Darwin 15.6.0
[0] npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "hot-server"
[0] npm ERR! node v4.4.4
[0] npm ERR! npm 
[0]  v2.15.1
[0] npm ERR! code
[0]  ELIFECYCLE
[0] npm ERR! play-splom@0.2.0 hot-server: `node -r babel-register server.js`
[0] npm ERR! Exit status 1
[0] npm ERR! 
[0] npm ERR! Failed at the play-splom@0.2.0 hot-server script 'node -r babel-register server.js'.`

**Comment by tatecarson** [comment]
I installed babel-register manually and now get this
' Error: Couldn't find preset "es2015" relative to directory "/Users/tatecarson/Desktop/play-splom-master"
[1]     at /Users/tatecarson/Desktop/play-splom-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:313:17
[1]     at Array.map (native)
[1]     at OptionManager.resolvePresets (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:305:20)
[1]     at OptionManager.mergePresets (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:288:10)
[1]     at OptionManager.mergeOptions (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:14)
[1]     at OptionManager.init (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-core/lib/transformation/file/options/option-manager.js:360:12)
[1]     at compile (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-register/lib/node.js:103:45)
[1]     at loader (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-register/lib/node.js:148:14)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/Users/tatecarson/Desktop/play-splom-master/node_modules/babel-register/lib/node.js:158:7)
[1]     at Module.load (module.js:458:32)'

**Comment by crucialfelix** [comment]
yeah I had those globally installed so didn't realize. I'm working on playsplom today and will fix.

Tou would also need to have scsynth installed in the vendor directory. I hadn't yet made sure it was ready for others to play with.

there is a build at https://github.com/experimentalDataAesthetics/play-splom/releases

thanks for the report !
